// <auto-generated/>
#nullable enable
namespace VenueIQ.App.Resources.Strings
{
    using System.Globalization;
    using System.Resources;

    public static class AppResources
    {
        private static ResourceManager? resourceMan;
        private static CultureInfo? resourceCulture;

        public static ResourceManager ResourceManager => resourceMan ??= new ResourceManager("VenueIQ.App.Resources.Strings.AppResources", typeof(AppResources).Assembly);

        public static CultureInfo? Culture { get => resourceCulture; set => resourceCulture = value; }
    }
}
